import MapKit
import Alamofire
import SwiftyJSON
import CoreLocation

class MapViewController: UIViewController, MKMapViewDelegate, CLLocationManagerDelegate, UISearchBarDelegate {
    
    /// Error code generated by Alamofire if no connection established
    let offlineErrorCode = -1004
    let getEvents = "http://192.168.1.65:54321/api/venue/search"
    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var mapView: MKMapView!
    
    // start all users in belfast
    let locationManager = CLLocationManager()
    var searchText = ""
    var venueArray = [String]()
    var annotation = MKPointAnnotation()
    var annotationArray: [MKPointAnnotation] = []
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.searchBar.delegate = self
        locationManager.requestWhenInUseAuthorization()
        establishLocationManager()
        let lat = 54.596516
        let lng = -5.930172
        let center = CLLocationCoordinate2D(latitude: lat, longitude: lng)
        let span = MKCoordinateSpanMake(0.05, 0.05)
        let region = MKCoordinateRegion(center: center, span: span)
        mapView.setRegion(region, animated: true)
    }
    
    func establishLocationManager(){
        searchBar.delegate = self
        locationManager.delegate = self
        locationManager.requestWhenInUseAuthorization()
        locationManager.requestAlwaysAuthorization()
        locationManager.desiredAccuracy = kCLLocationAccuracyBest
        locationManager.startUpdatingLocation()
        mapView.showsUserLocation = true
    }
    
    /// MARK: Location delegate methods
    func locationManager(manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        let location = locations.last
    }
    
    func locationManager(manager: CLLocationManager, didFailWithError error: NSError) {
        print("Failed to find user's location: \(error.localizedDescription)")
    }
    
    func searchBarSearchButtonClicked(searchBar: UISearchBar) {
        let annotationsToRemove = mapView.annotations.filter { $0 !== mapView.userLocation }
        mapView.removeAnnotations(annotationsToRemove)
        annotationArray.removeAll()
        searchText = searchBar.text!
        searchVenues()
        searchBar.endEditing(true)
    }
    
    func searchVenues() {
        
        let latitude:String = "\(locationManager.location!.coordinate.latitude)"
        let longitude:String = "\(locationManager.location!.coordinate.longitude)"
        
        let venueParameters = [ "venueType": searchText,
                                "latitude": latitude,
                                "longitude": longitude
        ]
        
        let alamoManager = Manager.sharedInstance
        alamoManager.session.configuration.HTTPAdditionalHeaders = [
            "Content-Type":"application/json"
        ]
        
        /// Alamofire request made with validated params returend with the response.
        alamoManager.request(.POST,getEvents,parameters: venueParameters, encoding: .JSON).validate().responseJSON { [weak self] serverResponse in
            
            /// SwiftyJSON used to easily parse JSON response, code sent by response includes message that is passed to message functions for display
            let errorData = serverResponse.data
            let responseData = String(data: errorData!, encoding: NSUTF8StringEncoding)
            
            if serverResponse.response!.statusCode != 200 {
                self!.alertMessage("None found", alertMessage: responseData!)
            }
            if let data = serverResponse.result.value {
                let jsonResult = JSON(data)
                for (index, object) in jsonResult {
                    let venueName = object["name"].stringValue
                    let venueAddress = object["formatted_address"].stringValue
                    let venueLati = object["lat"].double
                    let venueLngi = object["lng"].double
                    let venueLat = object["lat"].stringValue
                    let venueLng = object["lng"].stringValue
                    self!.venueArray.append(venueName)
                    self!.venueArray.append(venueAddress)
                    self!.venueArray.append(venueLat)
                    self!.venueArray.append(venueLng)
                
                    var points:CLLocationCoordinate2D = CLLocationCoordinate2DMake(venueLati!, venueLngi!);
                    self!.annotation.title = object["name"].stringValue
                    self!.annotation.subtitle = object["formatted_address"].stringValue
                    self!.annotation.coordinate = points
                    
                    self!.annotationArray.append(self!.annotation)
                }
                self!.mapView.addAnnotations(self!.annotationArray)
            }
            
        }
        
    }
    
    func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView? {
        let returnedAnnotationView:MKAnnotationView = PinAnnotation.createViewAnnotationForMap(self.mapView, annotation: annotation)
        let button = UIButton(type: .Custom)
        button.setTitle("More Info", forState: .Normal)
        button.addTarget(self, action: nil, forControlEvents: .TouchUpInside)
        returnedAnnotationView.rightCalloutAccessoryView = button
        return returnedAnnotationView
    }
    
    
    

    
    
    /// Popup alert that can be dismissed. Used to inform/warn the user as a result of their action not being accepted.
    ///
    /// - Parameter alertTitle: String used as title of the alert popup
    /// - Parameter alertMessage: String used as body of the alert popup
    func alertMessage(alertTitle: String, alertMessage: String){
        let alert = UIAlertController(title: alertTitle, message: alertMessage, preferredStyle: .Alert)
        alert.addAction(UIAlertAction(title: "OK", style: .Default) { _ in })
        self.presentViewController(alert, animated: true, completion: nil)
    }
}

//PinAnnotation class that implements the MKAnnotation protocol
class PinAnnotation:NSObject, MKAnnotation{
    var coordinate: CLLocationCoordinate2D
    var title: String?
    var subtitle: String?
    
    init(coordinate: CLLocationCoordinate2D, title: String, subtitle: String) {
        self.coordinate = coordinate
        self.title = title
        self.subtitle = subtitle
    }
    
    class func createViewAnnotationForMap(mapView:MKMapView, annotation:MKAnnotation)->MKAnnotationView{
        if let annotationView = mapView.dequeueReusableAnnotationViewWithIdentifier("PinAnnotation"){
            return annotationView
        }else{
            let returnedAnnotationView:MKPinAnnotationView = MKPinAnnotationView(annotation: annotation, reuseIdentifier:"PinAnnotation")
            returnedAnnotationView.pinTintColor = UIColor.redColor()
            returnedAnnotationView.animatesDrop = true
            returnedAnnotationView.canShowCallout = true
            return returnedAnnotationView
            
        }
    }
}