//
//  TableView.swift
//  majorprojectios
//
//  Created by Kelvin Harron on 30/08/2016.
//  Copyright © 2016 Kelvin Harron. All rights reserved.
//

import UIKit
import Alamofire
import SwiftyJSON

class TripView: UITableViewController {
    
    let statusURL = "http://localhost:54321/status"
    let getTripsURL = "http://localhost:54321/api/trip/"
    /// Error code generated by Alamofire if no connection established
    let offlineErrorCode = -1004
    
    override func viewDidAppear(animated: Bool) {
        checkStatus()
        getTripList()
    }
    
    @IBAction func logoutButton(sender: AnyObject) {
        moveToLogout()
    }
    
    /// Once called, moves to the welcome view
    func moveToLogout(){
        let storyboard = UIStoryboard(name: "Login", bundle: nil)
        let controller = storyboard.instantiateViewControllerWithIdentifier("welcome") as UIViewController
        self.presentViewController(controller, animated: true, completion: nil)
    }
    
  
    func checkStatus(){
        Alamofire.request(.GET, statusURL).validate().responseJSON { serverResponse in
            switch serverResponse.result {
            case .Success(let response):
                print("Server operational")
                break
            case .Failure(let error):
                self.alertMessage("No connection", alertMessage: "We can't reach the service at the moment. Please contact the admin.")
                break
            }
        }
    }
   
    
    func getTripList(){
        Alamofire.request(.GET, getTripsURL, parameters: nil, encoding: .JSON).validate().responseJSON { [weak self] serverResponse in
           
             let data = serverResponse.data
            let responseData = String(data: data!, encoding: NSUTF8StringEncoding)
            /// SwiftyJSON used to easily parse JSON response, code sent by response includes message that is passed to message functions for display
           
            
            
            if(serverResponse.response!.statusCode == 304) {
                if let value = serverResponse.result.value {
                    print(value)
                    let json = JSON(value)
                    print(json)
                    //print("TRIPNAME" + json.description)
                    if let tripname = json["tripname"].string {
                        
                    }
                }
            } else {
                ///self.alertMessage("Error", alertMessage: responseData)
            }
            
        }
    }
    
    /// Popup alert that can be dismissed. Used to inform/warn the user as a result of their action not being accepted.
    ///
    /// - Parameter alertTitle: String used as title of the alert popup
    /// - Parameter alertMessage: String used as body of the alert popup
    func alertMessage(alertTitle: String, alertMessage: String){
        let alert = UIAlertController(title: alertTitle, message: alertMessage, preferredStyle: .Alert)
        alert.addAction(UIAlertAction(title: "OK", style: .Default) { _ in })
        self.presentViewController(alert, animated: true, completion: nil)
    }
}